#include <stdio.h>
#include <stdlib.h>

/*
 * zio pipeline stage definitions
 */
enum zio_stage {
	ZIO_STAGE_OPEN			= 1 << 0,	/* RWFCI */

	ZIO_STAGE_READ_BP_INIT		= 1 << 1,	/* R---- */
	ZIO_STAGE_WRITE_BP_INIT		= 1 << 2,	/* -W--- */
	ZIO_STAGE_FREE_BP_INIT		= 1 << 3,	/* --F-- */
	ZIO_STAGE_ISSUE_ASYNC		= 1 << 4,	/* RWF-- */
	ZIO_STAGE_WRITE_COMPRESS	= 1 << 5,	/* -W--- */

	ZIO_STAGE_ENCRYPT		= 1 << 6,	/* -W--- */
	ZIO_STAGE_CHECKSUM_GENERATE	= 1 << 7,	/* -W--- */

	ZIO_STAGE_NOP_WRITE		= 1 << 8,	/* -W--- */

	ZIO_STAGE_DDT_READ_START	= 1 << 9,	/* R---- */
	ZIO_STAGE_DDT_READ_DONE		= 1 << 10,	/* R---- */
	ZIO_STAGE_DDT_WRITE		= 1 << 11,	/* -W--- */
	ZIO_STAGE_DDT_FREE		= 1 << 12,	/* --F-- */

	ZIO_STAGE_GANG_ASSEMBLE		= 1 << 13,	/* RWFC- */
	ZIO_STAGE_GANG_ISSUE		= 1 << 14,	/* RWFC- */

	ZIO_STAGE_DVA_THROTTLE		= 1 << 15,	/* -W--- */
	ZIO_STAGE_DVA_ALLOCATE		= 1 << 16,	/* -W--- */
	ZIO_STAGE_DVA_FREE		= 1 << 17,	/* --F-- */
	ZIO_STAGE_DVA_CLAIM		= 1 << 18,	/* ---C- */

	ZIO_STAGE_READY			= 1 << 19,	/* RWFCI */

	ZIO_STAGE_VDEV_IO_START		= 1 << 20,	/* RW--I */
	ZIO_STAGE_VDEV_IO_DONE		= 1 << 21,	/* RW--I */
	ZIO_STAGE_VDEV_IO_ASSESS	= 1 << 22,	/* RW--I */

	ZIO_STAGE_CHECKSUM_VERIFY	= 1 << 23,	/* R---- */

	ZIO_STAGE_DONE			= 1 << 24	/* RWFCI */
};

#define	ZIO_INTERLOCK_STAGES			\
	(ZIO_STAGE_READY |			\
	ZIO_STAGE_DONE)

#define	ZIO_INTERLOCK_PIPELINE			\
	ZIO_INTERLOCK_STAGES

#define	ZIO_VDEV_IO_STAGES			\
	(ZIO_STAGE_VDEV_IO_START |		\
	ZIO_STAGE_VDEV_IO_DONE |		\
	ZIO_STAGE_VDEV_IO_ASSESS)

#define	ZIO_VDEV_CHILD_PIPELINE			\
	(ZIO_VDEV_IO_STAGES |			\
	ZIO_STAGE_DONE)

#define	ZIO_READ_COMMON_STAGES			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_VDEV_IO_STAGES |			\
	ZIO_STAGE_CHECKSUM_VERIFY)

#define	ZIO_READ_PHYS_PIPELINE			\
	ZIO_READ_COMMON_STAGES

#define	ZIO_READ_PIPELINE			\
	(ZIO_READ_COMMON_STAGES |		\
	ZIO_STAGE_READ_BP_INIT)

#define	ZIO_DDT_CHILD_READ_PIPELINE		\
	ZIO_READ_COMMON_STAGES

#define	ZIO_DDT_READ_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_READ_BP_INIT |		\
	ZIO_STAGE_DDT_READ_START |		\
	ZIO_STAGE_DDT_READ_DONE)

#define	ZIO_WRITE_COMMON_STAGES			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_VDEV_IO_STAGES |			\
	ZIO_STAGE_ISSUE_ASYNC |			\
	ZIO_STAGE_CHECKSUM_GENERATE)

#define	ZIO_WRITE_PHYS_PIPELINE			\
	ZIO_WRITE_COMMON_STAGES

#define	ZIO_REWRITE_PIPELINE			\
	(ZIO_WRITE_COMMON_STAGES |		\
	ZIO_STAGE_WRITE_COMPRESS |		\
	ZIO_STAGE_ENCRYPT |			\
	ZIO_STAGE_WRITE_BP_INIT)

#define	ZIO_WRITE_PIPELINE			\
	(ZIO_WRITE_COMMON_STAGES |		\
	ZIO_STAGE_WRITE_BP_INIT |		\
	ZIO_STAGE_WRITE_COMPRESS |		\
	ZIO_STAGE_ENCRYPT |			\
	ZIO_STAGE_DVA_THROTTLE |		\
	ZIO_STAGE_DVA_ALLOCATE)

#define	ZIO_DDT_CHILD_WRITE_PIPELINE		\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_VDEV_IO_STAGES |			\
	ZIO_STAGE_DVA_THROTTLE |		\
	ZIO_STAGE_DVA_ALLOCATE)

#define	ZIO_DDT_WRITE_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_WRITE_BP_INIT |		\
	ZIO_STAGE_ISSUE_ASYNC |			\
	ZIO_STAGE_WRITE_COMPRESS |		\
	ZIO_STAGE_ENCRYPT |			\
	ZIO_STAGE_CHECKSUM_GENERATE |		\
	ZIO_STAGE_DDT_WRITE)

#define	ZIO_GANG_STAGES				\
	(ZIO_STAGE_GANG_ASSEMBLE |		\
	ZIO_STAGE_GANG_ISSUE)

#define	ZIO_FREE_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_FREE_BP_INIT |		\
	ZIO_STAGE_DVA_FREE)

#define	ZIO_DDT_FREE_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_FREE_BP_INIT |		\
	ZIO_STAGE_ISSUE_ASYNC |			\
	ZIO_STAGE_DDT_FREE)

#define	ZIO_CLAIM_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_DVA_CLAIM)

#define	ZIO_IOCTL_PIPELINE			\
	(ZIO_INTERLOCK_STAGES |			\
	ZIO_STAGE_VDEV_IO_START |		\
	ZIO_STAGE_VDEV_IO_ASSESS)

#define	ZIO_BLOCKING_STAGES			\
	(ZIO_STAGE_DVA_ALLOCATE |		\
	ZIO_STAGE_DVA_CLAIM |			\
	ZIO_STAGE_VDEV_IO_START)

const char *bits_string[64] = {
	"ZIO_STAGE_OPEN", "ZIO_STAGE_READ_BP_INIT", "ZIO_STAGE_WRITE_BP_INIT", "ZIO_STAGE_FREE_BP_INIT",
	"ZIO_STAGE_ISSUE_ASYNC", "ZIO_STAGE_WRITE_COMPRESS", "ZIO_STAGE_ENCRYPT", "ZIO_STAGE_CHECKSUM_GENERATE",
	"ZIO_STAGE_NOP_WRITE", "ZIO_STAGE_DDT_READ_START", "ZIO_STAGE_DDT_READ_DONE", "ZIO_STAGE_DDT_WRITE",
	"ZIO_STAGE_DDT_FREE", "ZIO_STAGE_GANG_ASSEMBLE", "ZIO_STAGE_GANG_ISSUE", "ZIO_STAGE_DVA_THROTTLE",
	"ZIO_STAGE_DVA_ALLOCATE", "ZIO_STAGE_DVA_FREE", "ZIO_STAGE_DVA_CLAIM", "ZIO_STAGE_READY",
	"ZIO_STAGE_VDEV_IO_START", "ZIO_STAGE_VDEV_IO_DONE", "ZIO_STAGE_VDEV_IO_ASSESS", "ZIO_STAGE_CHECKSUM_VERIFY",
	"ZIO_STAGE_DONE",
};


int
main(int ac, char **av) {
	unsigned long long v;

	if (ac != 2) {
		fprintf(stderr, "missing arg\n");
		exit(1);
	}
	v = strtoull(av[1], NULL, 0);

#define CHECK(flags) \
	if (v == (flags)) printf("Pre-defined stage mask: %s\n", #flags);

	CHECK(ZIO_INTERLOCK_STAGES)
	CHECK(ZIO_INTERLOCK_PIPELINE)
	CHECK(ZIO_VDEV_IO_STAGES)
	CHECK(ZIO_VDEV_CHILD_PIPELINE)
	CHECK(ZIO_READ_COMMON_STAGES)
	CHECK(ZIO_READ_PHYS_PIPELINE)
	CHECK(ZIO_READ_PIPELINE)
	CHECK(ZIO_DDT_CHILD_READ_PIPELINE)
	CHECK(ZIO_DDT_READ_PIPELINE)
	CHECK(ZIO_WRITE_COMMON_STAGES)
	CHECK(ZIO_WRITE_PHYS_PIPELINE)
	CHECK(ZIO_REWRITE_PIPELINE)
	CHECK(ZIO_WRITE_PIPELINE)
	CHECK(ZIO_DDT_CHILD_WRITE_PIPELINE)
	CHECK(ZIO_DDT_WRITE_PIPELINE)
	CHECK(ZIO_GANG_STAGES)
	CHECK(ZIO_FREE_PIPELINE)
	CHECK(ZIO_DDT_FREE_PIPELINE)
	CHECK(ZIO_CLAIM_PIPELINE)
	CHECK(ZIO_IOCTL_PIPELINE)
	CHECK(ZIO_BLOCKING_STAGES)

	for (int i = 0 ; i < 64 ; ++i) {
		if (v & (1ULL << i))
			printf("%3d %s\n", i, bits_string[i]);
	}
}
